# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo_collection.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(612, 608)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 29, 231, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 30, 201, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.file_push_button = QtWidgets.QPushButton(self.centralwidget)
        self.file_push_button.setGeometry(QtCore.QRect(460, 30, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.file_push_button.setFont(font)
        self.file_push_button.setObjectName("file_push_button")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 530, 80, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 530, 80, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.demos_collected_label = QtWidgets.QLabel(self.centralwidget)
        self.demos_collected_label.setGeometry(QtCore.QRect(20, 70, 211, 21))
        self.demos_collected_label.setObjectName("demos_collected_label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 110, 541, 301))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 57, 15))
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 420, 541, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.demo_status_title = QtWidgets.QLabel(self.frame_2)
        self.demo_status_title.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.demo_status_title.setObjectName("demo_status_title")
        self.demo_status = QtWidgets.QLabel(self.frame_2)
        self.demo_status.setGeometry(QtCore.QRect(200, 40, 101, 16))
        self.demo_status.setObjectName("demo_status")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(240, 70, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 612, 31))
        self.menubar.setObjectName("menubar")
        self.menuDemo = QtWidgets.QMenu(self.menubar)
        self.menuDemo.setObjectName("menuDemo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRecord = QtWidgets.QAction(MainWindow)
        self.actionRecord.setObjectName("actionRecord")
        self.actionCameras = QtWidgets.QAction(MainWindow)
        self.actionCameras.setObjectName("actionCameras")
        self.menubar.addAction(self.menuDemo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Folder in which to save the demo:"))
        self.file_push_button.setText(_translate("MainWindow", "..."))
        self.pushButton_2.setText(_translate("MainWindow", "Start"))
        self.pushButton_3.setText(_translate("MainWindow", "Stop"))
        self.demos_collected_label.setText(_translate("MainWindow", "Demos collected in this session:"))
        self.label_2.setText(_translate("MainWindow", "Cameras"))
        self.demo_status_title.setText(_translate("MainWindow", "Demo Status"))
        self.demo_status.setText(_translate("MainWindow", "Demo Status"))
        self.menuDemo.setTitle(_translate("MainWindow", "Demo"))
        self.actionRecord.setText(_translate("MainWindow", "Record"))
        self.actionCameras.setText(_translate("MainWindow", "Cameras"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
