# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(481, 222)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.startRecord = QtWidgets.QPushButton(self.centralwidget)
        self.startRecord.setGeometry(QtCore.QRect(20, 120, 141, 23))
        self.startRecord.setObjectName("startRecord")

        # Selection of folder in which to save demo (line edit)
        self.folder_to_save = QtWidgets.QLineEdit(self.centralwidget)
        self.folder_to_save.setGeometry(QtCore.QRect(20, 60, 321, 23))
        self.folder_to_save.setObjectName("folder_to_save")
        self.folder_save = '/home/hydra/sophie/whole_body_manipulation/logs' # Default folder
        self.folder_to_save.setText(self.folder_save)

        # Selection of folder in which to save demo (browse button)
        self.browse_push_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_push_button.setGeometry(QtCore.QRect(350, 60, 80, 23))
        self.browse_push_button.setObjectName("browse_push_button")

        # Selection of folder in which to save demo (label)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 321, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 481, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        ############################ Action attachment ######################################

        self.startRecord.clicked.connect(self.start_button_clicked) # start recording button

        self.browse_push_button.clicked.connect(self.browseFiles)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def start_button_clicked(self):
        """ 
        Action to start recording button
        """
        cmd_to_run = f"python ~/sophie/whole_body_manipulation/msc_tiago_ws/src/msc_tiago/scripts/wbc_teleop_left_collect_demo.py {self.folder_save} record"
        os.system(cmd_to_run)

    def browseFiles(self):
        """ 
        Action to open folder dialog
        """
        self.folder_save=QtWidgets.QFileDialog.getExistingDirectory(None, 'Select a folder:', self.folder_save, QtWidgets.QFileDialog.ShowDirsOnly)
        self.folder_to_save.setText(self.folder_save)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startRecord.setText(_translate("MainWindow", "Start Recording"))
        self.browse_push_button.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "Select folder in which to save the demo:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
